export const homeObjOne = {
    id: 'albums',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    heading: 'Handmade Photo Albums',
    name1: 'Denim Album',
    desc1: '',
    price1: '$74.99',
    button1: 'Add to cart',
    img1: require('../../images/album1.JPG'),
    name3: 'Colorful Album',
    desc3: '',
    price3: '$74.99',
    button3: 'Add to cart',
    img3: require('../../images/album2.JPG'),
    name2: 'Vintage Album',
    desc2: '',
    price2: '$74.99',
    button2: 'Add to cart',
    img2: require('../../images/album3.JPG'),
    dark: false,
    primary: false,
    darkText: true
};

export const homeObjTwo = {
    id: 'postcards',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    heading: 'Handmade Postcards',
    name1: 'Travel Postcard',
    desc1: '',
    price1: '$9.99',
    button1: 'Add to cart',
    img1: require('../../images/card1.JPG'),
    name2: 'Time Postcard',
    desc2: '',
    price2: '$12.99',
    button2: 'Add to cart',
    img2: require('../../images/card2.JPG'),
    name3: 'Dream Postcard',
    desc3: '',
    price3: '$9.99',
    button3: 'Add to cart',
    img3: require('../../images/card3.JPG'),
    dark: true,
    primary: true,
    darkText: false
};

export const homeObjThree = {
    id: 'exploadingBoxes',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    heading: 'Handmade Exploading Boxes',
    name1: 'Classy Box',
    desc1: '',
    price1: '$129.99',
    button1: 'Add to cart',
    img1: require('../../images/expbox1.JPG'),
    name2: 'Christmas Box',
    desc2: '',
    price2: '$129.99',
    button2: 'Add to cart',
    img2: require('../../images/expbox2.JPG'),
    name3: 'Snoopy Box',
    desc3: '',
    price3: '$129.99',
    button3: 'Add to cart',
    img3: require('../../images/expbox3.JPG'),
    dark: false,
    primary: false,
    darkText: true
};


export const homeObjFour = {
    id: 'matchboxes',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    heading: 'Handmade Mini Presents',
    name1: 'Graduation Matchbox',
    desc1: '',
    price1: '$7.99',
    button1: 'Add to cart',
    img1: require('../../images/minibox1.JPG'),
    name2: 'Travel MatchBox',
    desc2: '',
    price2: '$7.99',
    button2: 'Add to cart',
    img2: require('../../images/minibox2.JPG'),
    name3: 'Mushroom Matchbox',
    desc3: '',
    price3: '$7.99',
    button3: 'Add to cart',
    img3: require('../../images/minibox3.JPG'),
    dark: true,
    primary: true,
    darkText: false
};
